apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-deployment
spec:
  selector:
    matchLabels:
      app: phoenix
  replicas: 1
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      initContainers:
        - name: config-gen
          image: busybox
          command: ['sh', '-c', 'cp /phoenix/config.json /etc/phoenix/']
          volumeMounts:
            - name: init-config
              mountPath: /phoenix/config.json
              subPath: config.json
            - name: phoenix-config
              mountPath: /etc/phoenix
      containers:
        - name: phoenix-container
          image: owncloud/phoenix
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: phoenix-config
              mountPath: /srv/www/config.json
              subPath: config.json
      volumes:
        - name: phoenix-config
          emptyDir: {}
        - name: init-config
          configMap:
            name: phoenix-init-config
            defaultMode: 0744
