apiVersion: apps/v1
kind: Deployment
metadata:
  name: revad-deployment
spec:
  selector:
    matchLabels:
      app: revad
  replicas: 1
  template:
    metadata:
      labels:
        app: revad
    spec:
      containers:
        - name: revad-container
          image: cs3org/revad
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 20080
          command:
            - /go/bin/revad
            - -dev-dir
            - .
          workingDir: /go/src/github/cs3org/reva/examples/oc-phoenix
