apiVersion: apps/v1
kind: Deployment
metadata:
  name: revad-deployment
spec:
  selector:
    matchLabels:
      app: revad
  replicas: 1
  template:
    metadata:
      labels:
        app: revad
    spec:
      containers:
        - name: revad-container
          image: revad
          imagePullPolicy: Never
          ports:
            - containerPort: 20080